CREATE TABLE `clientes_multimarketing` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nome` text,
  `sexo` varchar(1) DEFAULT NULL,
  `data_nascimento` date DEFAULT NULL,
  `endereco` varchar(100) DEFAULT NULL,
  `numero` varchar(10) DEFAULT NULL,
  `complemento` varchar(50) DEFAULT NULL,
  `bairro` varchar(50) DEFAULT NULL,
  `cep` varchar(15) DEFAULT NULL,
  `cidade` varchar(50) DEFAULT NULL,
  `UF` varchar(2) DEFAULT NULL,
  `DDD` varchar(2) DEFAULT NULL,
  `celular` varchar(9) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `local` varchar(20) DEFAULT NULL,
  `enviado` tinyint(4) DEFAULT NULL,
  `recebido` tinyint(4) DEFAULT NULL,
  `data_envio` varchar(20) DEFAULT NULL,
  `chip` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `chip_fk` (`chip`),
  CONSTRAINT `chip_fk` FOREIGN KEY (`chip`) REFERENCES `chips_multimarketing` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10001 DEFAULT CHARSET=utf8;
