CREATE TABLE `movimentosunion` (
  `Tipo` varchar(45) NOT NULL,
  `Local` varchar(45) NOT NULL,
  `SKU` varchar(20) NOT NULL,
  `Data` varchar(11) DEFAULT NULL,
  `Hora` varchar(11) DEFAULT NULL,
  `Quantidade` int(11) DEFAULT NULL,
  `Valor` decimal(10,2) DEFAULT NULL,
  `TotalE` decimal(10,2) DEFAULT NULL,
  `Ticket` varchar(45) DEFAULT NULL,
  `CPFouCNPJ` varchar(45) DEFAULT NULL,
  `DataHora` datetime GENERATED ALWAYS AS (str_to_date(concat(`Data`,' ',`Hora`),'%Y-%m-%d %H:%i:%s')) VIRTUAL,
  `Dia` datetime GENERATED ALWAYS AS (str_to_date(concat(`Data`),'%Y-%m-%d')) VIRTUAL,
  `MC` varchar(45) GENERATED ALWAYS AS (substring_index(`SKU`,'-',1)) VIRTUAL,
  `Tam` varchar(5) GENERATED ALWAYS AS (if((locate('-',`SKU`) > 0),substring_index(`SKU`,'-',-(1)),'ND')) VIRTUAL,
  `isCPF` tinyint(4) GENERATED ALWAYS AS (if((char_length(trim(`CPFouCNPJ`)) > 15),0,1)) VIRTUAL,
  `CPFok` tinyint(4) GENERATED ALWAYS AS (if((left(`CPFouCNPJ`,14) = '000.000.000-00'),0,(substr(`CPFouCNPJ`,13,2) = concat(((((((((((substr(`CPFouCNPJ`,1,1) + (substr(`CPFouCNPJ`,2,1) * 2)) + (substr(`CPFouCNPJ`,3,1) * 3)) + (substr(`CPFouCNPJ`,5,1) * 4)) + (substr(`CPFouCNPJ`,6,1) * 5)) + (substr(`CPFouCNPJ`,7,1) * 6)) + (substr(`CPFouCNPJ`,9,1) * 7)) + (substr(`CPFouCNPJ`,10,1) * 8)) + (substr(`CPFouCNPJ`,11,1) * 9)) % 11) % 10),((((((((((substr(`CPFouCNPJ`,2,1) + (substr(`CPFouCNPJ`,3,1) * 2)) + (substr(`CPFouCNPJ`,5,1) * 3)) + (substr(`CPFouCNPJ`,6,1) * 4)) + (substr(`CPFouCNPJ`,7,1) * 5)) + (substr(`CPFouCNPJ`,9,1) * 6)) + (substr(`CPFouCNPJ`,10,1) * 7)) + (substr(`CPFouCNPJ`,11,1) * 8)) + (((((((((((substr(`CPFouCNPJ`,1,1) + (substr(`CPFouCNPJ`,2,1) * 2)) + (substr(`CPFouCNPJ`,3,1) * 3)) + (substr(`CPFouCNPJ`,5,1) * 4)) + (substr(`CPFouCNPJ`,6,1) * 5)) + (substr(`CPFouCNPJ`,7,1) * 6)) + (substr(`CPFouCNPJ`,9,1) * 7)) + (substr(`CPFouCNPJ`,10,1) * 8)) + (substr(`CPFouCNPJ`,11,1) * 9)) % 11) % 10) * 9)) % 11) % 10))))) VIRTUAL,
  `Total` decimal(12,2) GENERATED ALWAYS AS (if((`Quantidade` < 0),-(`TotalE`),`TotalE`)) VIRTUAL,
  KEY `idx_Movimentos_Tipo` (`Tipo`) USING BTREE,
  KEY `idx_Movimentos_Local` (`Local`) USING BTREE,
  KEY `idx_Movimentos_SKU` (`SKU`) USING BTREE,
  KEY `idx_Movimentos_Dia` (`Dia`) USING BTREE,
  KEY `idx_Movimentos_MC` (`MC`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
