select
	Local,
	SKU,
	CONCAT('="',ModeloCor,'"') as `Modelo-cor`,
	Tamanho,
	Colecao,
	Tipo,
	IF(DataCriacao='-','',DataCriacao) as `Data de criacao`,
	IF(PrimeiraMovimentacao='-','',PrimeiraMovimentacao) as `Primeira movimentacao`,
	IFNULL(Alvo,'') as `Alvo atual`,
	IF(DataCadastroAlvo='-','',DataCadastroAlvo) as `Data de cadastro do alvo`,
	IF(DataModificacaoAlvo='-','',DataModificacaoAlvo) as `Data de modificacao do alvo`,
	EEM as `Estoque em maos`,
	EET as `Estoque em transito`,
	DCE as `Dias com estoque`,
	UnidVendBr as `Unidades vendidas - bruto`,
	replace( round(ValorVendBr,2),
	'.',
	',' ) as `Valor total de vendas - bruto`,
	UnidVendLiq as `Unidades vendidas - liquido`,
	replace( round(ValorVendLiq,2),
	'.',
	',' ) as `Valor total de vendas - liquido`,
	Saidas,
	replace( round(CustoUni,2),
	'.',
	',' ) as `Custo unitario`,
	replace( round(PrecoOriginal,2),
	'.',
	',' ) as `Preco original`,
	replace( round(PrecoCorrente,2),
	'.',
	',' ) as `Preco corrente`,
	IFNULL(CampLocal,'') as `Campeao local`,
	if(PrimeiraDataCampLocal='-','',PrimeiraDataCampLocal) as `Primeira data de campeao local`,
	if(UltimaDataCampLocal='-','',UltimaDataCampLocal) as `Ultima data de campeao local`,
	VezesCampLocal as `Numero de vezes campeao local`,
	CampGlobal as `Campeao global`,
	IF(PrimeiraDataCampGlobal='-','',PrimeiraDataCampGlobal) as `Primeira data de campeao global`,
	IF(UltimaDataCampGlobal='-','',UltimaDataCampGlobal) as `Ultima data de campeao global`,
	IFNULL(VezesCampGlobal,'') as `Numero de vezes campeao global`
from
	new_eval;